plugins:
  - 'jest'
env:
  node: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  indent: ["error", "tab"]
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname", "__fixtures"] }]
  no-tabs: 0
