plugins:
  - 'jest'
  - 'fp'
env:
  node: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  indent: ["error"]
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  fp/no-let: "error"
  fp/no-mutation: "error"